; Firmware do Micromouse (ESP32-DEVKIT-V1)
;   pio run -e esp32dev       -> compila para o robô
;   pio test -e native        -> roda os testes no computador

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_ignore = *

[env:native]
platform = native
test_framework = unity
build_flags = --coverage
extra_scripts = post:cobertura.py
